# GitHub Actions CI workflow for Go project
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=5m
  build-examples:
    name: Build Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build examples
        run: make build-examples
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Dolt
        run: |
          bash -c 'curl -L https://github.com/dolthub/dolt/releases/download/v${DOLT_VERSION}/install.sh | bash'
          /usr/local/bin/dolt version
        env:
          DOLT_VERSION: 1.49.1
      - name: Build
        run: go build -v ./...
      - name: Test
        env:
          DOLT_BIN: /usr/local/bin/dolt
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
        run: go test -v ./... -race
